-- 開発環境用
update ADMIN_SETTING_MASTER 
set
    VALUE = 'C:\WORK\Vaults' 
where
    SETTING_ID = '001';


-- 新規追加
ALTER TABLE DRASAP.USER_MASTER ADD (
    SEARCH_SELCOL6 VARCHAR2(64),
    SEARCH_SELCOL7 VARCHAR2(64),
    SEARCH_SELCOL8 VARCHAR2(64),
    SEARCH_SELCOL9 VARCHAR2(64),
    SEARCH_SELCOL10 VARCHAR2(64),
    VIEW_SELCOL7 VARCHAR2(64),
    VIEW_SELCOL8 VARCHAR2(64),
    VIEW_SELCOL9 VARCHAR2(64),
    VIEW_SELCOL10 VARCHAR2(64),
    VIEW_SELCOL11 VARCHAR2(64),
    VIEW_SELCOL12 VARCHAR2(64),
    ONLY_NEWEST VARCHAR2(1),
    THUMBNAIL_SIZE VARCHAR2(1)
);

