-- 開発環境用
update ADMIN_SETTING_MASTER 
set
    VALUE = 'D:\Vaults'
where
    SETTING_ID = '001';


-- 新規追加
ALTER TABLE DRASAP.USER_MASTER ADD (
    SEARCH_SELCOL6 VARCHAR2(64),
    SEARCH_SELCOL7 VARCHAR2(64),
    SEARCH_SELCOL8 VARCHAR2(64),
    SEARCH_SELCOL9 VARCHAR2(64),
    SEARCH_SELCOL10 VARCHAR2(64),
    VIEW_SELCOL7 VARCHAR2(64),
    VIEW_SELCOL8 VARCHAR2(64),
    VIEW_SELCOL9 VARCHAR2(64),
    VIEW_SELCOL10 VARCHAR2(64),
    VIEW_SELCOL11 VARCHAR2(64),
    VIEW_SELCOL12 VARCHAR2(64),
    LATEST_REV_DISP_FLAG CHAR(1),
    THUMBNAIL_SIZE CHAR(1),
    RESULT_DISP_MODE CHAR(1)
);


-- カラム名変更
ALTER TABLE DRASAP.USER_MASTER RENAME COLUMN ONLY_NEWEST TO LATEST_REV_DISP_FLAG;

-- カラム型変更
ALTER TABLE DRASAP.USER_MASTER MODIFY (LATEST_REV_DISP_FLAG CHAR(1));
ALTER TABLE DRASAP.USER_MASTER MODIFY (THUMBNAIL_SIZE CHAR(1));
ALTER TABLE DRASAP.USER_MASTER MODIFY (RESULT_DISP_MODE CHAR(1));
